---
- name: Setup Ghostwriter
  hosts: jab_contact
  become: true
  vars_files:
    #Needs to contain {{ ansible_user }}
    - secrets.yml
  tasks:

    - name: Update Repos and Current Programs
      apt:
        name: "*"
        state: latest

    - name: Install Git, Docker/Compose, and other basic utilities.
      apt:
        pkg: 
        - curl
        - git
        - sudo
        - vim
        - gnupg
        - docker
        - docker-compose
        state: latest
      notify: restart_docker

    - name: Clone Ghostwriter 
      remote_user: "{{ ansible_user }}"
      ansible.builtin.git:
        repo: https://github.com/GhostManager/Ghostwriter.git
        dest: '/home/{{ ansible_user }}/ghostwriter/'
        clone: yes
        update: yes

  handlers:   
    - name: restart_docker
      service:
        name: docker 
        state: restarted
        enabled: true

